### ISSUE TITLE
docopt.DocoptLanguageError: unmatched '[' 

### ISSUE THREAD

**Issue by Sylvain303** [jazzband/docopt-ng#57]
Hello

This docstring was working before release `docopt-ng==0.9.0`
 
Note only the `Usage:` + up to the empty line should be parsed by docopt language. Unless you added new section name handling? 

By the way the error message doesn't help to figure out what is wrong.

## sample code

```python
#!/usr/bin/env python
"""
prepare an upgrade archive for upgrade_instance.py

Usage:
    ./prepare_upgrade.py create UPGRADE_FOLDER [--new]
    ./prepare_upgrade.py generate_sql DATE --sql-repos=INPUT_DIR_SQL [UPGRADE_DIR]
    ./prepare_upgrade.py fetch_releases RELEASE_PIPELINE [UPGRADE_DIR]
    ./prepare_upgrade.py show [UPGRADE_DIR]
    ./prepare_upgrade.py build [--upgrade-folder=UPGRADE_DIR] [--dest-zip=UPGRADE_ZIP]
    ./prepare_upgrade.py add (--sql|--repair) SQL_FILE [UPGRADE_DIR]
    ./prepare_upgrade.py convert_to_dep_txt [--old] [UPGRADE_DIR]
    ./prepare_upgrade.py tree [UPGRADE_DIR]
    ./prepare_upgrade.py install_helpers [--clean] [UPGRADE_DIR] [--ext_dir=INFRASTRUCTURE_DIR]

Env var:
    UPGRADE_DIR    if set, replace the UPGRADE_DIR parameter, so it can be ommited. If
                   both are present, parameter will be chosen.

Actions:
    create               Create an empty folder in UPGRADE_FOLDER (parent) that will contains
                         the upgrade tree Output the foldername suitable for UPGRADE_DIR env var
                         assignment.
                         --new will instruct to create a new_one if the folder exists with
                         the current date: upgrade_YYYY-MM-DD.2 (the last digit will
                         increase etc.)
    generate_sql         Take the SQL file in INPUT_DIR_SQL and filter from DATE included
                         in order to generate an sql folder tree into UPGRADE_DIR
    fetch_releases       Connect to VSTS to fetch the releases in prod based on RELEASE_PIPELINE.
                         This is a slow operation that take ~40s to complete. The outout yaml file
                         will be saved in UPGRADE_DIR.
    show                 Explain what is in UPGRADE_DIR and validate.
    build                Create the zip archive UPGRADE_ZIP based on the content of the
                         UPGRADE_DIR.  If UPGRADE_ZIP is not given the zip will be generated
                         in to the parent forled (aka: UPGRADE_FOLDER)
    add                  Add a new sql file manually to the UPGRADE_DIR. In sql/ dir if --sql
                         at the end with continuous order. In repair/ if --repair, with no
                         specific order.
    convert_to_dep_txt   For internal transitional conversion dep_version.txt format from releases.yaml.
                         Outputs to stdout.
    tree                 Display UPGRADE_DIR as a tree view.
    install_helpers      Copy helpers into UPGRADE_DIR. If --clean is present remove all helper first.
"""

from docopt import docopt

args = docopt(docstring=__doc__)

print(args)
```

## stacktrace

```
python bug_docopt-ng.py create prepare_upgrade 2>&1 | sed -e 's/cloudiway/mycode/'
Traceback (most recent call last):
  File "/home/sylvain/code/mycode/upgrade_instance/bug_docopt-ng.py", line 47, in <module>
    args = docopt(docstring=__doc__)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 913, in docopt
    pattern = parse_pattern(formal_usage(sections.usage_body), options)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 608, in parse_pattern
    result = parse_expr(tokens, options)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 617, in parse_expr
    seq_0: list[Pattern] = parse_seq(tokens, options)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 638, in parse_seq
    atom = parse_atom(tokens, options)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 657, in parse_atom
    matched_pattern = pattern(*parse_expr(tokens, options))
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 617, in parse_expr
    seq_0: list[Pattern] = parse_seq(tokens, options)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 638, in parse_seq
    atom = parse_atom(tokens, options)
  File "/home/sylvain/.local/lib/python3.10/site-packages/docopt/__init__.py", line 659, in parse_atom
    raise tokens.error("unmatched '%s'" % token)
docopt.DocoptLanguageError: unmatched '['
```

**Comment by NickCrews** [comment]
Hey @Sylvain303 thanks for the issue!

[See the changelog entry for 0.9.0](https://github.com/jazzband/docopt-ng/blob/master/CHANGELOG.md#changed).

The issue is that one of the lines in your docstring starts with `--new`. Starting in 0.9.0, any line that begins with a `-` is now parsed as an option. So just change your line wrapping or add some quotes or something and it works fine.

I agree that the error message is terrible. Ideally it would be better, but no one has yet taken the time to improve this. There are several issues in this repo about that. If you feel motivated then help would be appreciated!
